// <auto-generated />
using System;
using ACTIVA_IT.WEB.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace PruebaNexos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200719054423_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PruebaNexos.Context.Models.Atencion", b =>
                {
                    b.Property<int>("IdAtencion")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdDoctor");

                    b.Property<int>("IdPaciente");

                    b.HasKey("IdAtencion");

                    b.HasIndex("IdDoctor");

                    b.HasIndex("IdPaciente");

                    b.ToTable("Atencion");
                });

            modelBuilder.Entity("PruebaNexos.Context.Models.Doctor", b =>
                {
                    b.Property<int>("IdDoctor")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<string>("Especialidad");

                    b.Property<int>("IdHospital");

                    b.Property<string>("Nombre");

                    b.Property<string>("NumCredencial");

                    b.HasKey("IdDoctor");

                    b.HasIndex("IdHospital");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("PruebaNexos.Context.Models.Hospital", b =>
                {
                    b.Property<int>("IdHospital")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion");

                    b.Property<string>("Nombre");

                    b.Property<string>("Telefono");

                    b.HasKey("IdHospital");

                    b.ToTable("Hospital");
                });

            modelBuilder.Entity("PruebaNexos.Context.Models.LogDatos", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Evento");

                    b.Property<string>("Excepcion");

                    b.Property<DateTime>("Fecha");

                    b.Property<string>("Mensaje");

                    b.HasKey("IdLog");

                    b.ToTable("LogDatos");
                });

            modelBuilder.Entity("PruebaNexos.Context.Models.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<string>("CodigoPostal");

                    b.Property<string>("Nombre");

                    b.Property<string>("NumSeguroSocial");

                    b.Property<string>("Telefono");

                    b.HasKey("IdPaciente");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("PruebaNexos.Context.Models.Atencion", b =>
                {
                    b.HasOne("PruebaNexos.Context.Models.Doctor", "Doctor")
                        .WithMany("Atencion")
                        .HasForeignKey("IdDoctor")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PruebaNexos.Context.Models.Paciente", "Paciente")
                        .WithMany("Atencion")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PruebaNexos.Context.Models.Doctor", b =>
                {
                    b.HasOne("PruebaNexos.Context.Models.Hospital", "Hospital")
                        .WithMany("Doctor")
                        .HasForeignKey("IdHospital")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
